import type { Metadata } from "next";

import ProviderLayout from "@/providers";
import { ChildProp } from "@/types/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildProp) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ProviderLayout>{children}</ProviderLayout>
      </body>
    </html>
  );
}
